name: "Prepare build environment"
description: "Free disk space and setup nix"

inputs:
  attic_token:
    description: "The attic authentication token"
    required: true
  github_token:
    description: "The GitHub authentication token"
    required: true

runs:
  using: "composite"
  steps:
    - name: Free Disk Space (Ubuntu)
      uses: jlumbroso/free-disk-space@main
      with:
        tool-cache: true

    - name: Create netrc file for private cache authentication
      shell: bash
      run: |
        sudo mkdir -p /etc/nix
        echo "machine attic.jakobkukla.xyz password ${{ inputs.attic_token }}" | sudo tee /etc/nix/netrc > /dev/null

    - name: Install Nix
      uses: ./.github/actions/install-nix
      with:
        github_token: ${{ inputs.github_token }}

