name: "Install Nix"
description: "Wrapper around lix-gha-installer-action"

inputs:
  github_token:
    description: "The GitHub authentication token"
    required: true

runs:
  using: "composite"
  steps:
    - name: Install Lix
      uses: samueldr/lix-gha-installer-action@v2026-06-15
      with:
        github_access_token: ${{ inputs.github_token }}
        extra_nix_config: |
          fallback = true
          http-connections = 128
          max-substitution-jobs = 128
          substituters = https://attic.jakobkukla.xyz/system?priority=43 https://nix-community.cachix.org?priority=41 https://numtide.cachix.org?priority=42 https://cache.nixos.org/
          trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= system:nVcKbJl9QpDnXrVPUGItRzmFvyHYf+64JBSaKkKoZGc= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs= numtide.cachix.org-1:2ps1kLBUWjxIneOy1Ik6cQjb41X0iXVXeHigGmycPPE=
