name: "Build machines"

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/README.md'
      - 'TODO.md'
      - 'LICENSE'
      - '.gitignore'

jobs:
  build:
    strategy:
      matrix:
        machine: [ aztec, cache, inferno, mirage, triton, vertigo ]
    uses: ./.github/workflows/reusable-base.yml
    with:
      machine: ${{ matrix.machine }}
      update: false
    secrets: inherit

  promote:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Promote to stable
        uses: ./.github/actions/promote-stable

