# See https://lgug2z.com/articles/building-and-privately-caching-x86-and-aarch64-nixos-systems-on-github-actions/

name: "Cachix"
on:
  push:
    branches:
      - master
    paths-ignore:
      - 'README.md'
      - 'TODO.md'
      - 'LICENSE'
      - '.gitignore'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Prepare build environment
        uses: ./.github/actions/prepare-build-environment
        with:
          attic_token: ${{ secrets.ATTIC_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build system
        # FIXME: nix-fast-build hangs indefinitely while copying some sources
        # run: nix run github:Mic92/nix-fast-build -- --skip-cached --no-nom --flake ".#nixosConfigurations.matebook.config.system.build.toplevel"
        run: nix build ".#nixosConfigurations.matebook.config.system.build.toplevel"

      - name: Push system to private cache
        uses: ./.github/actions/push-to-cache
        with:
          attic_token: ${{ secrets.ATTIC_TOKEN }}

