name: "build"

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'README.md'
      - 'TODO.md'
      - 'LICENSE'
      - '.gitignore'

jobs:
  build:
    strategy:
      matrix:
        machine: [ matebook, pc ]
    uses: ./.github/workflows/build-and-push.yml
    with:
      machine: ${{ matrix.machine }}
      update: false

