name: "Cachix"
on:
  push:
    branches:
      - master
      # TODO: remove these when merged
      - multi
    paths-ignore:
      - 'README.md'
      - 'TODO.md'
      - 'LICENSE'
      - '.gitignore'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Free Disk Space (Ubuntu)
      uses: jlumbroso/free-disk-space@main
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |
          experimental-features = nix-command flakes
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
    - name: Install nix-build-uncached
      run: nix-env -f '<nixpkgs>' -iA nix-build-uncached
    - uses: cachix/cachix-action@v12
      with:
        name: jakobkukla
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix-build-uncached ./ci.nix
