name: "Cachix"
on:
  push:
    branches:
      - master
      # TODO: remove these when merged
      - btrfs
      - multi
    paths-ignore:
      - 'README.md'
      - 'TODO.md'
      - 'LICENSE'
      - '.gitignore'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v18
    - uses: cachix/cachix-action@v11
      with:
        name: jakobkukla
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build .#nixosConfigurations.matebook.config.system.build.toplevel
