name: "Update machines"

on:
  workflow_dispatch: # allows manual triggering
  schedule:
    - cron: '30 04 * * MON' # runs weekly on Monday at 04:30

jobs:
  update:
    strategy:
      matrix:
        machine: [ matebook, pc ]
    uses: ./.github/workflows/reusable-base.yml
    with:
      machine: ${{ matrix.machine }}
      update: true

