name: "update"

on:
  workflow_dispatch: # allows manual triggering
  schedule:
    - cron: '30 04 * * MON' # runs weekly on Monday at 04:30

jobs:
  build:
    strategy:
      matrix:
        machine: [ matebook, pc ]
    uses: ./.github/workflows/build-and-push.yml
    with:
      machine: ${{ matrix.machine }}
      update: true

